### ISSUE TITLE
На win не работает запуск команды без расширения

### ISSUE THREAD

**Issue by nixel2007** [artbear/1commands#13]
Имею 1bdd.bat
Создаю команду
```bsl
	Команда = Новый Команда;
	Команда.УстановитьКоманду("1bdd");
	Команда.Исполнить();
```

Ловлю эксепшн  "не найден указанный файл"

**Comment by artbear** [comment]
Это не баг, это фича :)

ИМХО нет такого приложения 1bdd.exe или 1bdd.com
Есть приложение cmd.exe, которое и нужно запустить с передачей параметра `1bdd`

Возможно, для упрощения работы пользователей библиотеки сделать метод
`Команда.УстановитьКомандуСистемы("1bdd")`
которая реально вызовет
```bsl
Команда.УстановитьКоманду("cmd");
Команда.ДобавитьПараметр("/c 1bdd");
```

@nixel2007 @EvilBeaver Что скажете по этой идее?

**Comment by artbear** [comment]
Естественно, для Windows и Linux нужно выбирать разные имена приложения командных процессоров

**Comment by nixel2007** [comment]
Нененененене. Инкапсуляцию хочу. Вот прям совсем хочу.
У меня есть 1bdd.bat и 1bdd (который sh). Смд по умолчанию умеет искать файлы с дополнением имени по зарегистрированному расширению (есть отдельная переменная среды).

Хочу навсегда забыть об этом аде с cmd /c
Если скриптописатель ~упоротый~ упёртый и хочет творить эту магию с cmd /c /// sh -c (и ему нужны какие-то доп флаги или явно нужно указать интерпретатор) - то флаг ему в руки. А как обыватель я не хочу про это думать. На винде есть стандартный командный процессор. На линуксе он дефакто тоже есть - sh. Пусть вся эта магия будет скрыта.

**Comment by artbear** [comment]
Желание понятно. Сам люблю магию.

А теперь подумай над реализацией:
как определить, что вызывается команда системы, а не отдельное приложение 1bdd ?

я пока не вижу простого пути для получения ответа на этот вопрос :(

вызывать отдельный where/which ? ИМХО изврат

Как?

**Comment by artbear** [comment]
Я тебе и предложил магию
`Команда.УстановитьКомандуСистемы("1bdd")`

просто и инкапсулировано.

**Comment by nixel2007** [comment]
Возможно это вопрос для @EvilBeaver

Разве СоздатьПроцесс самого движка не должен разруливать это?
И отвлеченный вопрос - кто смотрит в эту переменную среды с расширениями? Это делает сам cmd? Или оно глубже в ядре?

Ну и банальная идея реализации - 
Если ЭтоВиндоус Тогда
    СтрокаЗапуска = "cmd /c " + СтрокаЗапуска;
Иначе
    СтрокаЗапуска = "sh -c " + СтрокаЗапуска;
КонецЕсли;

Только зашить это в сам 1commands. Причем и у меня и в v8runner это так и было. Зачем ты убрал?
Плюс убран анализ потока ошибок, если код возврата <> 0 - тоже неудобно. Но это тема отдельной ишузы

**Comment by nixel2007** [comment]
Я видимо пока читал - пропустил твое первое сообщение :(

> ИМХО нет такого приложения 1bdd.exe или 1bdd.com

есть 1bdd.bat, а bat - зарегистрированное расширение для запуска из cmd.

> Возможно, для упрощения работы пользователей библиотеки нужно сделать метод
Команда.УстановитьКомандуСистемы("1bdd")
которая реально вызовет для Windows

я не уверен, что следует делать это отдельной командой, а не инкапсулировать это в обычном выполнении команды. Лишняя нагрузка. В общем случае я не знаю, что у меня лежит в моем PATH - oscript.exe или какой-то oscript.bat, который вызывает `call path/to/oscript.exe -encoding=utf-8`

Аналогично с любой другой программой. Обязывая пользователя выбирать между командой установки запускаемого приложения мы заставляем его знать устройство этого приложения и тип точки входа.

**Comment by artbear** [comment]
>Возможно это вопрос для @EvilBeaver
Разве СоздатьПроцесс самого движка не должен разруливать это?

ИМХО не должно, это лишняя сложность, которая должна разруливаться клиентом универсального метода СоздатьПроцесс.

>И отвлеченный вопрос - кто смотрит в эту переменную среды с расширениями? Это делает сам cmd? Или оно глубже в ядре?

Ты про какую переменную среды?

>Ну и банальная идея реализации - 
```bsl
Если ЭтоВиндоус Тогда
    СтрокаЗапуска = "cmd /c " + СтрокаЗапуска;
Иначе
    СтрокаЗапуска = "sh -c " + СтрокаЗапуска;
КонецЕсли;
```

>Только зашить это в сам 1commands. Причем и у меня и в v8runner это так и было. Зачем ты убрал?

Я думал над этим, решил, что запуск через cmd не для всех процессов удобен. Например, как ловить потоки ошибок приложения в этом случае??

Предлагаю подобное поведение зашить при использовании метода `Команда.УстановитьКомандуСистемы("1bdd")`

ИМХО будет четкий и понятный выбор поведения.
Разные клиенты смогут выбирать разное поведение :) и все будут довольны.

>Плюс убран анализ потока ошибок, если код возврата <> 0 - тоже неудобно. Но это тема отдельной ишузы

Проверка кода возврата на 0 и вызов исключения не всегда удобен.
API должна давать разные варианты использования.

Для анализа/реализации подобного поведения давно создана https://github.com/artbear/1commands/issues/6 
Предлагаю там обсуждать

**Comment by artbear** [comment]
>Я видимо пока читал - пропустил твое первое сообщение :(
А я это сообщение пропустил

>> ИМХО нет такого приложения 1bdd.exe или 1bdd.com

>есть 1bdd.bat, а bat - зарегистрированное расширение для запуска из cmd.

Я уже выше писал - а как мне внутри реализации узнать, bat или exe вызывается? :(

>я не уверен, что следует делать это отдельной командой, а не инкапсулировать это в обычном выполнении команды. Лишняя нагрузка. В общем случае я не знаю, что у меня лежит в моем PATH - oscript.exe или какой-то oscript.bat, который вызывает `call path/to/oscript.exe -encoding=utf-8`

>Аналогично с любой другой программой. Обязывая пользователя выбирать между командой установки запускаемого приложения мы заставляем его знать устройство этого приложения и тип точки входа.

C твоей точкой зрения также согласен.

Мне хочется дать возможность использовать оба подхода с минимальным расхождением API
1 - запуск любого консольного приложения (run как run.exe) без участия командного процессора
2 - запуск любых команд системы (1bdd как 1bdd,bat) прозрачно с помощью командного процессора.

/cc @allustin @EvilBeaver @dmpas @sosnae Что скажете?

**Comment by EvilBeaver** [comment]
в 1С для этого аж два отдельных метода. ЗапуститьПриложение и КомандаСистемы. Второй, в любом случае втыкает cmd.exe в начале.

**Comment by artbear** [comment]
@EvilBeaver Про 1С понятно, у меня такая же логика.

Так ты лично за разделение логики на 2 метода или нет?

**Comment by EvilBeaver** [comment]
наверное да. хотя, если 1commands всегда будет использовать cmd.exe - тоже заработает

**Comment by artbear** [comment]
@EvilBeaver какой ты гибкий как уж :)

Повторюсь:
Так ты лично за разделение логики на 2 метода или нет?

**Comment by EvilBeaver** [comment]
@artbear ну не надо тут "гибких" на меня переадресовывать, мы-то знаем, кто владеет этой медалью, ага 😄 

Я вопроса не понял про два метода. Что спрашивали-то?

**Comment by artbear** [comment]
Предлагаю реализовать следующий вариант:
+ по умолчанию запуск команд будет через cmd/sh, как и предлагает @nixel2007 
+ но это поведение можно отменить через вызов спец.метода `ОтключитьИсполнениеЧерезКомандыСистемы` или `ВключитьИсполнениеБезКомандСистемы`, как хочется мне.

ИМХО все довольны.

/cc @nixel2007 @EvilBeaver 

Готов сейчас уже реализовать.

**Comment by nixel2007** [comment]
Да, хороший вариант. 👍

**Comment by artbear** [comment]
@nixel2007 Какой вариант именования метода отключения наиболее подходящ?

**Comment by nixel2007** [comment]
Я предлагаю первый вариант, но в сразу в паре с методом ВключитьИсполнениеЧерезКомандыСистемы

Если уж использовать негатив в имени метода, то пусть он будет в мягкой "глагольной" форме. Иначе будет ОтключитьИсполнениеБезКомандСистемы - двойное отрицание.

**Comment by nixel2007** [comment]
ну или УстановитьИсполнениеЧерезКомандыСистемы(Истина/Ложь)

**Comment by artbear** [comment]
>УстановитьИсполнениеЧерезКомандыСистемы(Истина/Ложь)

Продано.

**Comment by artbear** [comment]
При работе с vanessa-runner нарвался на подобную проблему https://github.com/silverbulleters/vanessa-runner/pull/77#issuecomment-283642680

А здесь простой exe-файл, не батник.

Текущее решение из этого ишуза также подошло.
