### ISSUE TITLE
Зависание при выполнени

### ISSUE THREAD

**Issue by Khorevaa** [artbear/1commands#14]
Дано: limux
Запуск: команды gitsync для хранилища
Зависание на 5 версии. 
Видимо переполнение потока вывода т.к. выполнении тоже команды в консоле не приводит к зависанию

**Comment by artbear** [comment]
Почему здесь ишуз заведен, а не в репо гитсинка?
Лог гитсинк приложи, плиз.

**Comment by Khorevaa** [comment]
Вот это не работает 

`
	КомандаЗапуска = Новый Команда;
	КомандаЗапуска.УстановитьКоманду("oscript");
	ПутьКБиблиотекеСкриптов = ПолучитьЗначениеСистемнойНастройки("lib.system");
	ПутьКGitSync = ОбъединитьПути(ПутьКБиблиотекеСкриптов, "gitsync","src","gitsync.os") ;
	КомандаЗапуска.ДобавитьПараметр(ПутьКGitSync);

	КомандаЗапуска.ДобавитьПараметр(ПутьКХранилищю1С);
	КомандаЗапуска.ДобавитьПараметр(URLРепозитория);
	КомандаЗапуска.ДобавитьПараметр(ПутьКРабочейКопии);
	
	КомандаЗапуска.ДобавитьПараметр(СтрШаблон("-branch %1", ИмяВетки));
	КомандаЗапуска.ДобавитьПараметр(СтрШаблон("-debug %1",  Отладка));
	КомандаЗапуска.ДобавитьПараметр(СтрШаблон("-v8version %1", ВерсияПлатформы));
	КомандаЗапуска.ДобавитьПараметр(СтрШаблон("-email can" ));
	//КомандаЗапуска.ДобавитьПараметр(СтрШаблон("-tmp-dir %1", ВременныйКаталог));
	//КомандаЗапуска.ДобавитьПараметр(СтрШаблон("-useautotags %1", АвтоматическаяУстановкаМеток));
	//КомандаЗапуска.ДобавитьПараметр(СтрШаблон("-push-every-n-commits %1", ОтправкаИзмененийКаждыеNКоммитов));
	РезультатВыполнения = КомандаЗапуска.Исполнить();
	
	Сообщить("Вывод команды выполнения Gitsync: " + КомандаЗапуска.ПолучитьВывод());
	Возврат РезультатВыполнения;`

**Comment by nixel2007** [comment]
ты уверен что оно именно зависает? Сейчас 1commands накапливает в себе вывод, а потом выводит его через единое сообщить().

**Comment by Khorevaa** [comment]
Да 99% зависает. Ждал около 2-х часов ...

**Comment by Khorevaa** [comment]
хранилище маленькое 18 версий (изменения мелочевные)  Через запуск приложения проходит за 1 минуту примерно

**Comment by artbear** [comment]
PS @nixel2007 Я поправил твой коммент https://github.com/artbear/1commands/issues/14#issuecomment-273073015
Исправил расцветку кода.
Посмотри, плиз, на будущее, как оформлять куски 1С/Os кода

**Comment by nixel2007** [comment]
@artbear видимо, ты хотел пингануть не меня, а @Khorevaa

**Comment by artbear** [comment]
Ага, опечатался.

**Comment by artbear** [comment]
@Khorevaa Навскидку вижу разницу в 2х запусках.
Для вариант ЗапуститьПриложение - указан запуск в каталоге `ПутьКРабочейКопии` 
  +`ЗапуститьПриложение(СтрокаЗапуска, ПутьКРабочейКопии, Истина, РезультатВыполнения);`
А через команду нет подобного указания.

**Comment by Khorevaa** [comment]
Значит кусок кода копировал не корректно! -) в общем вроде как все должно быть одинаково..

**Comment by Khorevaa** [comment]
@artbear Спасибо за помощь по подсветке.. А то самого бесило.... Несколько раз пытался сделать корректно!  теперь буду знать)

**Comment by artbear** [comment]
@Khorevaa Можешь привести 2 точных примера кода, один из которых зависает, а второй работает?

**Comment by Khorevaa** [comment]
Добрый день, прогнал еще раз указнные куски кода..  Они являются корректными с точки зрения зависания. Так же на ubuntu диагностировал спам от 1С следующего характара

```
(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «pixmap»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «murrine»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «pixmap»,

(1cv8s:2474): Gtk-WARNING **: Загружаемый модуль тем не найден в module_path: «pixmap»,

```

**Comment by Khorevaa** [comment]
Видимо спам от 1С переполяет буфер потока вывода...

**Comment by artbear** [comment]
Совместно с @ret-Phoenix исследовали проблему зависания.
Подтвердили, что баг с участием 1commands для гитсинка есть :(

Происходит зависание все-таки в момент показа множества сообщений при включенном режиме `core.autocrlf=true` 

Но смогли найти вариант обхода :)

Нужно для репозиториев гит включать режим `core.autocrlf=false` !! Локально или глобально.

В этом случае `git add` не генерит кучу сообщений о неверных переводах строк и успешно выполняет свою работу.

@ret-Phoenix проблему своего зависания решил.

@Khorevaa Сможешь у себя проверить такое решение?

Я получил сценарий точного срабатывания бага и буду пытаться его исправить.
@nixel2007 сможешь проверить гит-раннер для указанного сценария?

**Comment by nixel2007** [comment]
@artbear gitrunner не использует 1коммандс пока.
Какой именно сценарий нужно проверить? Саму способность работы и прохождение имеющихся тестов?

**Comment by artbear** [comment]
@nixel2007 Нужно проверить поведение гитраннер "коммит и адд" через гитраннер в описанных условиях.

**Comment by Khorevaa** [comment]
@artbear Конечно проверю с указанным условием. Но думаю не поможет т.к. конфигурация была минимальная для тестов т.к. 2 объекта всего. Я думаю тут больше проблема с буфером потока вывода.

**Comment by artbear** [comment]
Реализовано поведение для обхода бага движка. https://github.com/artbear/1commands/issues/21

Конкретно по гитсинк - проблема актуальна только при включенном режиме `git` `core.autocrlf=true`
Без этого режима гитсинк работает правильно.

Задачу закрываю.
