### ISSUE TITLE
Прием массива параметров команды командного файла

### ISSUE THREAD

**Issue by artbear** [artbear/1commands#25]
Часто параметры очередной команды Командного файла собираются предварительно в массив параметров.
Например, 
```bsl
ПараметрыКоманды = Новый Массив;
 ПараметрыКоманды.Добавить("git status");
 ПараметрыКоманды.Добавить("-b");
 ПараметрыКоманды.Добавить("-s");
 ```

Удобно добавить метод `ДобавитьПараметры(Знач МассивПараметров)`
>~~Было бы удобно добавлять подобный набор параметров в методе `ДобавитьКоманду(Знач Команда)`~~
~~В итоге этот метод будет принимать один из 2х видов параметров~~
~~+ Строка - уже собранная строка параметров команды~~
~~+ Массив - массив параметров команды. которые нужно собрать в одну строку`~~

И станет удобнее пользоваться классом "КомандныйФайл"
Например, в gitsync

**Comment by nixel2007** [comment]
В java мире для этого служат методы add и addAll

**Comment by artbear** [comment]
Переведи, плиз.
У нас есть КомандныйФайл.ДобавитьКоманду(Знач СтрокаКоманды), что предлагаешь изменить?

**Comment by nixel2007** [comment]
Я не про команду, а про её параметры

**Comment by artbear** [comment]
Все равно не понял. 
Жду расшифровки, лучше с примером

**Comment by nixel2007** [comment]
У нас с тобой наверное терминология разная. Для меня команда - это исполняемый файл, например git. Параметры команды - это её аргументы. Строка запуска команды - это команда плюс её аргументы в одной строке. 

Соответственно есть три метода для одного запуска команды :
* УстановитьСтрокуЗапуска, когда мы одним методом заполняем и команду и её аргументы 
* ДобавитьКоманду + n вызовов ДобавитьПараметрКоманды() на каждый параметр 
* ДобавитьКоманду + 1 вызов ДобавитьПараметрыКоманды(), куда передаётся массив параметров.

**Comment by artbear** [comment]
Терминология совпадает.
С примером стало понятно.

Да, лучше делать отдельный метод `ДобавитьПараметры(Знач МассивПараметров)`

**Comment by artbear** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [1](https://trello.com/c/48F9Vu4g/2-1)

**Comment by artbear** [comment]
Выполнено
