### ISSUE TITLE
Падает прогон тестов через opm test

### ISSUE THREAD

**Issue by artbear** [artbear/1commands#29]
+ Падает на appveyor
+ у пользователей также проблемы https://gitter.im/EvilBeaver/oscript-library?at=59e60922614889d475c690b5
  + https://yadi.sk/i/QM8_c1CV3NqFpQ

**Comment by artbear** [comment]
@nixel2007 @EvilBeaver @dmpas **Проблема в запуске через `opm test`**

В этом случае сначала opm грузит системные библиотеки, в т.ч. и 1commands, и только потом загружается библиотека из рабочего каталога.

Часть лога `package-loader.os`, 
+ где `C:\OneScript\lib` - системный каталог пакетов, 
+ а `C:\projects\1commands` - это рабочей каталог разработки
```
ПриЗагрузкеБиблиотеки C:\OneScript\lib\1commands
класс Команда, файл C:\OneScript\lib\1commands\src\Команда.os
класс КомандныйФайл, файл C:\OneScript\lib\1commands\src\КомандныйФайл.os

ПриЗагрузкеБиблиотеки C:\OneScript\lib\tempfiles
модуль ВременныеФайлы, файл C:\OneScript\lib\tempfiles\ВременныеФайлы.os
класс МенеджерВременныхФайлов, файл C:\OneScript\lib\tempfiles\ВременныеФайлы.os
ПриЗагрузкеБиблиотеки C:\OneScript\lib\fs
ОбработатьСтруктуруКаталоговПоСоглашению
модуль ФС, файл C:\OneScript\lib\fs\Модули\ФС.os

ПриЗагрузкеБиблиотеки C:\projects\1commands
класс Команда, файл C:\projects\1commands\src\Команда.os
класс КомандныйФайл, файл C:\projects\1commands\src\КомандныйФайл.os

ПриЗагрузкеБиблиотеки C:\OneScript\lib\1bdd
```
2 последних библиотеки загружаются, т.к. в test.os прописано 
```bsl
#Использовать ".."
#Использовать 1bdd
```
а так классы уже ранее загружены, повторная загрузка библиотеки ничего не делает, что и приводит к багу.

**Если же прогонять тесты без участия opm, напрямую через `oscript tasks/test.os`**, 

то все в порядке и загрузка библиотек идет в обратном, правильном порядке,
как и прописано в файле `test.os`

лог следующий
```
ПриЗагрузкеБиблиотеки C:\projects\1commands
класс Команда, файл C:\projects\1commands\src\Команда.os
класс КомандныйФайл, файл C:\projects\1commands\src\КомандныйФайл.os

ПриЗагрузкеБиблиотеки C:\OneScript\lib\logos
ПриЗагрузкеБиблиотеки C:\OneScript\lib\asserts
ПриЗагрузкеБиблиотеки C:\OneScript\lib\tempfiles

ПриЗагрузкеБиблиотеки C:\OneScript\lib\1bdd

ПриЗагрузкеБиблиотеки C:\OneScript\lib\strings

ПриЗагрузкеБиблиотеки C:\OneScript\lib\1commands
класс Команда, файл C:\OneScript\lib\1commands\src\Команда.os
класс КомандныйФайл, файл C:\OneScript\lib\1commands\src\КомандныйФайл.os
```

**Comment by artbear** [comment]
В итоге, получается, для разработки системных библиотек нельзя юзать `opm test`
либо нужно предпринимать какие-то меры для защиты от подобного поведения :(

**Comment by nixel2007** [comment]
Эту проблему обсуждали и решали еще год назад. Надо тестировать что-то, что используется как зависимость в фреймворке тестирования - подключай свой файл через ЗагрузитьСценарий

**Comment by artbear** [comment]
ЗагрузитьСценарий использует те же библиотеки, т.к. он находится в одном сеансе oscript.
и это не решает проблему.
opm test как раз так и работает, насколько я понимаю.

**Comment by nixel2007** [comment]
ЗагрузитьСценарий вообще не использует библиотек. Он создает новый экземпляр класса/модуля по указанному пути, ему наплевать, что там в снаружи происходит.

тестируешь классы 1коммандс - загружаешь 1коммандс.

**Comment by artbear** [comment]
@nixel2007 Ты уверен в 'ЗагрузитьСценарий вообще не использует библиотек'
У нас же одно пространство имен.

@EvilBeaver @dmpas А вы что скажете?

**Comment by artbear** [comment]
@nixel2007 Ты какой вариант предлагаешь для 1коммандс? я что-то не понял.

**Comment by artbear** [comment]
Кстати, в типовом Jenkinsfile для билд.оскрипт.ио Андрей удачно использует именно `oscript tasks/test.os` и пакеты прогоняются без ошибок, в т.ч. и 1тестраннер, например.

**Comment by nixel2007** [comment]
@artbear я имею ввиду, что если у тебя уже загружен через Использовать класс КомандныйФайл, то через загрузить сценарий ты подключишь конкретную версию с диска, а не с каталога либ. Библиотеки, импортируемые внутри КомандныйФайл, понятное дело, полезут из каталога либ, но тебе и не надо их тестировать - они просто должным быть прописаны в зависимостях с нужными версиями

**Comment by artbear** [comment]
В целом результат - для правильного тестирования библиотек, которые есть и в разработке, и в каталоге lib движка на машине, нужно 
+ юзать запуск через `oscript tasks/test.os`, а не `opm test`
+ первой строкой в этом файле нужно писать `Использовать ".."`
  + вместо `".."` нужно писать правильный путь к исходникам классов/модулей
+ а уже далее писать `Использовать 1bdd` и/или `Использовать 1testrunner`

И дополнительно (но необязательно):
+ если в разработке меняется API разрабатываемой библиотеки, которое юзается в 1бдд или 1тестраннере и/или используемых ими библиотек, 
  + тогда нужно менять код использования API в нужных местах других библиотек
  + добиваться прохождения всех тестов/фич
  + и делать пулл-реквест в соответствующей библиотеки
+ без подобной доработки тесты, скорее всего, будут падать и нельзя будет гарантировать правильность разработки

 обсудили эту с @nixel2007 
других вариантов не нашли

**Comment by artbear** [comment]
И кстати, после недавнего PR по PowerShell тесты AppVeyor стали падать.

А после исправления согласно комментариям выше эти тесты опять стали зелеными.

Я вчера также добавил типовой Jenkinsfile для CI на build.oscript.io
