### ISSUE TITLE
Ошибка Внешнее исключение (System.ArgumentException): Item has already been added. Key in dictionary: ‘HOME’ Key being added: ‘home’}

### ISSUE THREAD

**Issue by PashaMak** [artbear/1commands#35]
На версии 1.21 проблема при коммите через SourceTree v 2* ошибка:
Ошибка Внешнее исключение (System.ArgumentException): Item has already been added. Key in dictionary: ‘HOME’ Key being added: ‘home’}

**Comment by EvilBeaver** [comment]
Это уже кто-то рассматривал и даже фиксил... Вроде бы там проблема с переменными окружения.
А можно пример кода на 1Скрипте, который вызывает эту ошибку?

**Comment by PashaMak** [comment]
Ошибка возникает при запуске прекоммита

**Comment by PashaMak** [comment]
После отката onescript до версии 1.9 прекоммит ошибка прошла

**Comment by EvilBeaver** [comment]
1.19 может быть?

**Comment by artbear** [comment]
@PashaMak Давно исправлено в 1.3.4
Смотри https://github.com/artbear/1commands/releases/tag/1.3.4
Обновляйся

**Comment by PashaMak** [comment]
// Запустить команду в операционной системе с ожиданием ее выполнения 
//
// Параметры:
//   Параметры - Массив - Массив строковых аргументов, передаваемых в командную
//		строку. Добавляются после исполняемого файла.
//
//  Возвращаемое значение:
//   Число - Код возврата приложения
//
Функция ЗапуститьИПодождать()

	СтрокаЗапуска = СформироватьСтрокуЗапускаПроцесса();
    
	ПерехватыватьПотоки = Истина;

	Если КодировкаВывода = Неопределено Тогда
		Процесс = СоздатьПроцесс(СтрокаЗапуска, РабочийКаталог, ПерехватыватьПотоки, ПерехватыватьПотоки);
	Иначе
		Процесс = СоздатьПроцесс(СтрокаЗапуска, РабочийКаталог, ПерехватыватьПотоки, ПерехватыватьПотоки, КодировкаВывода);		
	КонецЕсли;    
    Процесс.Запустить();
	
	ПолучитьВыводПокаПроцессИсполняется(Процесс);

	КодВозврата = Процесс.КодВозврата;
	ПроверитьКодВозврата(КодВозврата);

    Возврат КодВозврата;
    
КонецФункции

ошибка в строке
Процесс = СоздатьПроцесс(СтрокаЗапуска, РабочийКаталог, ПерехватыватьПотоки, ПерехватыватьПотоки, КодировкаВывода);

**Comment by artbear** [comment]
Еще раз:
>@PashaMak Давно исправлено в 1.3.4
Смотри https://github.com/artbear/1commands/releases/tag/1.3.4
Обновляйся

рекомендую обновиться на версию 1.3.4 и проверить поведение на ней

**Comment by PashaMak** [comment]
После обновления до версии 1.34 проблема прошла
