### ISSUE TITLE
Уменьшить мусорные логи

### ISSUE THREAD

**Issue by EvilBeaver** [artbear/1commands#37]
Сейчас вывод процесса в логах очень сложно оценить, поскольку он дублируется в трех местах.

получается, что лог замусорен результатами выхлопа процесса и сложно определять - это тот же запуск процесса просто 3 раза повторен, или был другой запуск процесса.

Например отладочное сообщение "в цикле - " ничего не говорит пользователю. Это чисто разработческий костыль на момент, когда не было отладчика.

**Comment by artbear** [comment]
Выполнено.
