### ISSUE TITLE
Добавить возможность запуска команды в фоне

### ISSUE THREAD

**Issue by khorevaa** [artbear/1commands#38]
Сейчас можно только запустить и подождать! 
Надо добавить метод `ЗапуститьПроцесс` который будет возвращать процесс для дальнейшей обработки

**Comment by artbear** [comment]
Зачем нужен метод ЗапуститьПроцесс() ?
пользовательский кейс какой? чем будет отличаться от старта процесса из движка?

**Comment by khorevaa** [comment]
Сейчас это просто удобство 1коммандс для создания процессов с параметрами. Уже использую в проекте AutoUpdateIB -  как скопированный класс и небольшой допилкой

**Comment by artbear** [comment]
@khorevaa если выполнено, закрой, пожалуйста.

Готовлюсь к выпуску релиза
