### ISSUE TITLE
Добавить возможноть не перехватывать ввод и вывод

### ISSUE THREAD

**Issue by khorevaa** [artbear/1commands#40]
Сейчас принудительно перехватывается ввод и вывод процесса
Предлагаю сделать возможность это переопределять, для того чтобы запущенные процессы писали в текущую консоль

**Comment by khorevaa** [comment]
Плох тем что - убирает возможность вывода в текущую консоль как есть!  
Что собственно и надо. Готов сделать -) Не хочу дублировать код 1commands или писать аналогичную либу )

**Comment by artbear** [comment]
@khorevaa ишуз решен? если да, закрой его.

Готовлюсь к выпуску релиза
