### ISSUE TITLE
Нужен релиз 1.3.6 или 1.4

### ISSUE THREAD

**Issue by khorevaa** [artbear/1commands#42]
@artbear 
Новый функционал хочу использовать  уже

**Comment by artbear** [comment]
@khorevaa сделаю, закрой решенные ишузы

Готовлюсь к выпуску релиза

**Comment by artbear** [comment]
@khorevaa Перед выпуском релиза нужно разрулить https://github.com/artbear/1commands/issues/43

**Comment by artbear** [comment]
Сейчас выпущу релиз
