### ISSUE TITLE
Режим с правильными кодом возврата и неправильными кодами возврата.

### ISSUE THREAD

**Issue by artbear** [artbear/1commands#6]
В случае получения неправильного кода возврата должно выбрасываться исключение с текстом вывода команды.

API:
+ `УстановитьПравильныйКодВозврата(Знач КодВозврата);`
+ `УстановитьДиапазонПравильныхКодовВозврата(Знач МинимальныйКодВозврата, Знач МаксимальныйКодВозврата);`

**Comment by artbear** [comment]
Родился новый вариант API для реализации
`ПроверитьИсполнение(Знач ОжидаемыйКодВозврата = 0)`

@nixel2007 @EvilBeaver Что скажете?

**Comment by nixel2007** [comment]
Вместо Исполнить()?

**Comment by artbear** [comment]
Будет 2 метода
- `Функция Исполнить`
- `Процедура ПроверитьИсполнение(Знач ОжидаемыйКодВозврата = 0)`

**Comment by nixel2007** [comment]
Исполнить перестанет возвращать код возврата?

**Comment by nixel2007** [comment]
А, я понял, что ты хочешь. Ты хочешь кидать эксепшн внутри 1commands.

Имхо, первый вариант чище в плане апи.

**Comment by artbear** [comment]
>Функция Исполнить 

!!

**Comment by artbear** [comment]
Какой первый?
Обозначь, плиз, свой предпочитаемый вариант АПИ для сабжа.

**Comment by nixel2007** [comment]
В первом посте

**Comment by artbear** [comment]
А мне как раз кажется, что первый вариант слишком искусственный.
И его неудобно будет вызывать, код вызова коряво будет выглядеть.
А вот вариант с ПроверитьИсполнение вполне удобен и нагляден
